[package]
name = "visidata-loaders"
description = "File format loaders for VisiData"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
visidata-core = { workspace = true }
visidata-ext-protocol = { workspace = true }
csv = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
rusqlite = { workspace = true }
calamine = { workspace = true }
parquet = { workspace = true }
arrow = { workspace = true, features = ["ipc"] }
scraper = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
