[package]
name = "visidata-tui"
description = "TUI rendering for VisiData using ratatui"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
visidata-core = { workspace = true }
visidata-loaders = { workspace = true }
visidata-scripting = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
unicode-width = { workspace = true }
